[package]
name = "ace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
clap = { version = "4.2.4", features = ["derive"] }
env_logger = "0.10.0"
hex = "0.4.3"
home = "0.5.5"
log = "0.4.17"
random_str = "0.1.1"
regex = "1.8.1"
reqwest = { version = "0.11.16", features = ["cookies", "json", "rustls-tls", "blocking"], default-features = false }
reqwest_cookie_store = "0.5.0"
rpassword = "7.2.0"
serde = "1.0.160"
serde_derive = "1.0.160"
serde_yaml = "0.9.21"
simple-home-dir = "0.1.2"
