[package]
name = "ace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.3"
cbc = "0.1.2"
chrono = "0.4.31"
chrono-tz = "0.8.3"
clap = { version = "4.4.4", features = ["derive"] }
colored = "2.0.4"
dialoguer = "0.11.0"
dotenv = "0.15.0"
env_logger = "0.10.0"
hex = "0.4.3"
home = "0.5.5"
lazy_static = "1.4.0"
log = "0.4.20"
once_cell = "1.18.0"
rand = "0.8.5"
random_str = "0.1.2"
regex = "1.9.5"
reqwest = { version = "0.11.20", features = ["cookies", "json", "rustls-tls", "blocking"], default-features = false }
reqwest_cookie_store = "0.6.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_derive = "1.0.188"
serde_yaml = "0.9.25"
soup = "0.5.1"
sqlite = "0.31.1"
