use serde_derive::Deserialize;
use serde_derive::Serialize;
#[derive(Serialize, Deserialize)]
pub struct CodeTemplate {
    pub alias: String,
    pub lang: String,
    pub path: String,
    pub suffix: String,
    pub before_script: String,
    pub script: String,
    pub after_script: String,
}
pub const CODEFORCES: [&'static str; 2] = ["codeforces", "cf"];
pub const ATCODER: [&'static str; 3] = ["atcoder", "ac", "atc"];
pub enum ProgramLanguage {
    C,
    Cpp,
    Java,
    Python,
    Rust,
    Kotlin,
    Go,
    CSharp,
    D,
    Ruby,
    Scala,
    Haskell,
    Perl,
    Php,
    OCaml,
    Delphi,
    Pascal,
    Lua,
    JavaScript,
    TypeScript,
    FSharp,
    QSharp,
    Swift,
    R,
    Julia,
    Tcl,
    Io,
    Factor,
    Text,
    Zsh,
    Bash,
    PowerShell,
    Cobol,
    Awk,
    Nim,
    Vim,
    V,
    Zig,
    Dart,
    VisualBasic,
    Fortran,
    Lisp,
    Erlang,
}
