name: ACE Auto Tag

on:
  push:
    branches: [ master ]

jobs:
  new-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SebRollen/toml-action@v1.0.2
        id: read_toml
        with:
          file: 'Cargo.toml'
          field: 'package.version'
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ steps.read_toml.outputs.value }}
          tag_exists_error: false
          message: "Release ${{ steps.read_toml.outputs.value }}"