name: ACE Release

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    env:
      RUST_BACKTRACE: full
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            output: ace
            dist: ace-linux-amd64.zip
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            output: ace
            dist: ace-linux-arm64.zip
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            output: ace.exe
            dist: ace-windows-amd64.zip
          - os: macos-latest
            target: x86_64-apple-darwin
            output: ace
            dist: ace-macos-amd64.zip
          - os: macos-latest
            target: aarch64-apple-darwin
            output: ace
            dist: ace-macos-arm64.zip
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        target: ${{ matrix.target }}
        toolchain: nightly
        default: true
        override: true
    
    - name: Install cross
      run: cargo install cross

    - name: Cargo build ${{ matrix.target }}
      if: ${{ !contains(matrix.os, 'ubuntu') }}
      timeout-minutes: 120
      run: cargo build -r --target ${{ matrix.target }}

    - name: Cross build ${{ matrix.target }}
      if: ${{ contains(matrix.os, 'ubuntu') }}
      timeout-minutes: 120
      run: cross build -r --target ${{ matrix.target }}

    - name: Rename file
      run: | 
        mv target/${{ matrix.target }}/release/${{ matrix.output }} ./${{ matrix.output }}
        zip ${{ matrix.dist }} ${{ matrix.output }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: my-artifact
        path: ${{ matrix.dist }}
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: my-artifact
        path: artifacts
    - name: Display structure of downloaded files
      run: ls -al artifacts
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ${{ github.event.release.body }}
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
