name: ACE Test

on:
  pull_request:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-macos:
    runs-on: macos-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        target: ${{ matrix.target }}
        toolchain: nightly
        default: true
        override: true

    - name: Build ${{ matrix.target }}
      timeout-minutes: 120
      shell: bash
      run: cargo build --target ${{ matrix.target }} 

    - name: Test ${{ matrix.target }}
      if: matrix.target == 'x86_64-apple-darwin'
      timeout-minutes: 120
      shell: bash
      run: cargo test --target ${{ matrix.target }} 
  build-windows:
    runs-on: windows-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          #- aarch64-pc-windows-msvc
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        target: ${{ matrix.target }}
        toolchain: nightly
        default: true
        override: true

    - if: ${{ matrix.target == 'aarch64-pc-windows-msvc' }}
      run: |
        echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\Llvm\x64\bin" >> $GITHUB_PATH
        echo "RUSTFLAGS=-C target-feature=+crt-static" >> $GITHUB_ENV
      shell: bash
      
    - name: Build ${{ matrix.target }}
      timeout-minutes: 120
      shell: bash
      run: cargo build --target ${{ matrix.target }} 

    - name: Test ${{ matrix.target }}
      if: matrix.target == 'x86_64-pc-windows-msvc'
      timeout-minutes: 120
      shell: bash
      run: cargo test --target ${{ matrix.target }} 

  build-linux:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        target: ${{ matrix.target }}
        toolchain: nightly
        default: true
        override: true

    - name: Install cross
      run: cargo install cross

    - name: Build ${{ matrix.target }}
      timeout-minutes: 120
      shell: bash
      run: cross build --target ${{ matrix.target }}

    - name: Test ${{ matrix.target }}
      if: matrix.target == 'x86_64-unknown-linux-gnu'
      timeout-minutes: 120
      shell: bash
      run: cross test --target ${{ matrix.target }}
  
