name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-apple-darwin
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --target ${{ matrix.target }} --verbose
    - name: Run tests
      run: cargo test --verbose
